site_name: MKDOCS2TE

theme:
  name: material
  features:
    - search.suggest
    - search.highlight
    - content.code.copy
    - navigation.indexes

repo_url: https://github.com/AzureLearn1/mkdocs2
repo_name: mkdocs2

plugins:
  - search
